//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GazLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int idWorker { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string idGender { get; set; }
        public int idAccess { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Access Access { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
